<a href="https://colab.research.google.com/github/Rudraksh919/PractisePublic/blob/main/Task_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Basics of Numpy

Import numpy

In [2]:
import numpy as np

###Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Make a rank 1 array from a python list, print its shape, and change one of its elements.

In [3]:

arr1 = np.array([1,2,3,4,5]) # Creating Array of Rank 1

arr1[3] = 6 #Changing value of element at index 4

print(arr1.size) # Printing Size of Array


5


Do the same with a rank 2 arrray

In [4]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

arr2[1][2] = 55

print(arr2.shape)

(2, 5)


Make arrays with the following inbuilt numpy functions - zeroes, ones, full,
eye, random

###Array indexing

In [2]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]

arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
newarr3 = arr3[:2,1:3]
print(newarr3)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [7]:
#try changing the original array by changing its sliced part
newarr3[1,1] = 55

In [19]:
# explore and try different types of slicing techniques here
arr4 = arr3[:-1,-3:-1]
print(arr4)

[[2 3]
 [6 7]]


In [3]:
# a given numpy array a
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

# an array of indices
b = np.array([0, 2, 0, 1])

In [5]:
# Select one element from each row of a using the indices in b
print(a[b[2],b[1]])

3


In [ ]:
# Mutate one element from each row of a using the indices in b
a[b[0],b[0]] = 45

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [2]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# Create a NumPy array of shape (4, 4) with integer values ranging from 1 to 16.
# Using Boolean indexing, create a new array that contains only the elements of the original array that are divisible by 3.
# Finally, print the original array, the Boolean mask, and the filtered array.

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

###Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [3]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [4]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Do the elementwise sum using two different methods
# Method 1(Direct)
z = x + y

# Method 2(by loop)
z = np.array([[0,0],[0,0]], dtype=np.float64)

i = 0
while i < 2:
    j=0
    while j < 2:
        z[i,j]= x[i,j] + y[i,j]
        j += 1
    i+=1




In [5]:
# Do the elementwise difference (x-y) using two different methods
# Method 1(Direct)
z = x - y

# Method 2(by loop)
z = np.array([[0,0],[0,0]], dtype=np.float64)

i = 0
while i < 2:
    j=0
    while j < 2:
        z[i,j]= x[i,j] - y[i,j]
        j += 1
    i+=1

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [7]:
# Do the elementwise product using two different methods
# Method 1(Direct)
z = x * y

# Method 2(by loop)
z = np.array([[0,0],[0,0]], dtype=np.float64)

i = 0
while i < 2:
    j=0
    while j < 2:
        z[i,j]= x[i,j] * y[i,j]
        j += 1
    i+=1

[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Do the elementwise division (x/y) using two different methods

# Method 1(Direct)
z = x / y

# Method 2(by loop)
z = np.array([[0,0],[0,0]], dtype=np.float64)

i = 0
while i < 2:
    j=0
    while j < 2:
        z[i,j]= x[i,j] / y[i,j]
        j += 1
    i+=1



In [ ]:
# Do the elementwise squareroot





In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# take the dot product of vectors v and w

z = v * w

i=0
g=0
while i<2:
    g += z[i]
    i+=1

219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [9]:
# do the same using @

z = v @ w

219


In [ ]:
# Do the matrix multiplication x*y

z = x * y 



Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [14]:
x = np.array([[1,2],[3,4]])

# Compute sum of all elements; prints "10"
print(x.sum())

# Compute sum of each column; prints "[4 6]"
print(x.sum(0))

# Compute sum of each row; prints "[3 7]"
print(x.sum(1))


10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [18]:
x = np.array([[1,2],[3,4]])

# take the transpose of above matrix
x.T

[[1 2]
 [3 4]]


###Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [21]:
x = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18], [20, 22, 24]])
v = np.array([1, 2, 3])

# Task 1: Use a loop to add the vector v to each row of the matrix x, and store the result in a new matrix y.
# Task 2: Modify the loop to subtract the vector v from each row of the matrix x, and store the result in another matrix z.
# Task 3: Print all three matrices (x, y, and z).

y = np.empty_like(x)

for i in range(4):
    y[i,:] = x[i,:] + v 

z = np.empty_like(x)

for i in range(4):
    z[i,:] = x[i,:] - v

print(x)
print(y)
print(z)



[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]
 [21 24 27]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [24]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]
 [21 24 27]]


In [26]:
# Repeat Task 1, 2, and 3 without using a for loop

y = x + vv
z = x - vv

print(x)
print(y)
print(z)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]
 [21 24 27]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


In [29]:
### Exercise -1

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 2, 1])

# Without using any explicit loops, subtract the vector from each column of the matrix using broadcasting.
# Calculate the square of each element in the resulting matrix.
# Find the row-wise sum of the squared elements.
# Print the resulting matrix after subtraction, the squared matrix, and the row-wise sums.

a = matrix - vector
print(a)

a *= a
print(a)

print(a.sum(1))

[[0 0 2]
 [3 3 5]
 [6 6 8]]
[[ 0  0  4]
 [ 9  9 25]
 [36 36 64]]
[  4  43 136]


In [30]:
### Exercise - 2

A = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
B = np.array([1, 3, 5])


# Multiply each row of A element-wise by B using broadcasting.
# Find the mean of each column in the resulting matrix.
# Create a Boolean mask identifying elements in the resulting matrix that are greater than the column mean.
# Use this mask to extract and print the elements that satisfy the condition.
C=A*B
print(C)

print((C.sum(1))/3)



[[ 2 12 30]
 [ 8 30 60]
 [14 48 90]]
[14.66666667 32.66666667 50.66666667]
